# Generated by Django 4.1.8 on 2023-05-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_transaccion_paypal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
