# Generated by Django 4.1.8 on 2023-05-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conexion',
            old_name='monto',
            new_name='importe',
        ),
    ]
