# Generated by Django 4.1.8 on 2023-04-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_conexion_consumido'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexion',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
